name: 'Sync TODOs to GitHub Issues'

on:
  push:
    branches: [main, master]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: 'Generate Issues'
        uses: alstr/todo-to-issue-action@v5
        with:
          identifiers: >
            [
              {"name": "BUG", "labels": ["bug"]},
              {"name": "FIXME", "labels": ["fixme"]},
              {"name": "TODO", "labels": ["todo"]},
              {"name": "OPTIMIZE", "labels": ["optimize"]},
              {"name": "REFACTOR", "labels": ["refactor"]},
              {"name": "TEST", "labels": ["test"]},
              {"name": "IDEA", "labels": ["idea"]},
              {"name": "DOC", "labels": ["documentation"]}
            ]
          ignore: 'node_modules, .next, .vscode, public, dist, build, .git'
          auto_assign: true
          close_issues: true
